/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiV1FeedbackRouteImport } from './routes/api/v1/feedback'
import { Route as ApiV1WidgetConfigRouteImport } from './routes/api/v1/widget-config'
import { Route as AppPProjectIdRouteImport } from './routes/app/p.$projectId'
import { Route as ApiProjectsProjectIdExportRouteImport } from './routes/api/projects/$projectId.export'
import { Route as AppPProjectIdIndexRouteImport } from './routes/app/p.$projectId/index'
import { Route as AppPProjectIdInsightsRouteImport } from './routes/app/p.$projectId/insights'
import { Route as AppPProjectIdInstallRouteImport } from './routes/app/p.$projectId/install'
import { Route as AppPProjectIdSettingsRouteImport } from './routes/app/p.$projectId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeedbackRoute = ApiV1FeedbackRouteImport.update({
  id: '/api/v1/feedback',
  path: '/api/v1/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WidgetConfigRoute = ApiV1WidgetConfigRouteImport.update({
  id: '/api/v1/widget-config',
  path: '/api/v1/widget-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPProjectIdRoute = AppPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const ApiProjectsProjectIdExportRoute =
  ApiProjectsProjectIdExportRouteImport.update({
    id: '/api/projects/$projectId/export',
    path: '/api/projects/$projectId/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPProjectIdIndexRoute = AppPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdInsightsRoute = AppPProjectIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdInstallRoute = AppPProjectIdInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdSettingsRoute = AppPProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/team': typeof AppTeamRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/widget-config': typeof ApiV1WidgetConfigRoute
  '/app/p/$projectId': typeof AppPProjectIdRouteWithChildren
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/app/p/$projectId/insights': typeof AppPProjectIdInsightsRoute
  '/app/p/$projectId/install': typeof AppPProjectIdInstallRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId/': typeof AppPProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/team': typeof AppTeamRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/widget-config': typeof ApiV1WidgetConfigRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/app/p/$projectId/insights': typeof AppPProjectIdInsightsRoute
  '/app/p/$projectId/install': typeof AppPProjectIdInstallRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId': typeof AppPProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/team': typeof AppTeamRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/widget-config': typeof ApiV1WidgetConfigRoute
  '/app/p/$projectId': typeof AppPProjectIdRouteWithChildren
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/app/p/$projectId/insights': typeof AppPProjectIdInsightsRoute
  '/app/p/$projectId/install': typeof AppPProjectIdInstallRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId/': typeof AppPProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/setup'
    | '/signup'
    | '/api/health'
    | '/app/account'
    | '/app/new'
    | '/app/team'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/app/'
    | '/api/v1/feedback'
    | '/api/v1/widget-config'
    | '/app/p/$projectId'
    | '/api/projects/$projectId/export'
    | '/app/p/$projectId/insights'
    | '/app/p/$projectId/install'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/signup'
    | '/api/health'
    | '/app/account'
    | '/app/new'
    | '/app/team'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/app'
    | '/api/v1/feedback'
    | '/api/v1/widget-config'
    | '/api/projects/$projectId/export'
    | '/app/p/$projectId/insights'
    | '/app/p/$projectId/install'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/setup'
    | '/signup'
    | '/api/health'
    | '/app/account'
    | '/app/new'
    | '/app/team'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/app/'
    | '/api/v1/feedback'
    | '/api/v1/widget-config'
    | '/app/p/$projectId'
    | '/api/projects/$projectId/export'
    | '/app/p/$projectId/insights'
    | '/app/p/$projectId/install'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BSlugRoute: typeof BSlugRoute
  FSlugRoute: typeof FSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiV1FeedbackRoute: typeof ApiV1FeedbackRoute
  ApiV1WidgetConfigRoute: typeof ApiV1WidgetConfigRoute
  ApiProjectsProjectIdExportRoute: typeof ApiProjectsProjectIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedback': {
      id: '/api/v1/feedback'
      path: '/api/v1/feedback'
      fullPath: '/api/v1/feedback'
      preLoaderRoute: typeof ApiV1FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/widget-config': {
      id: '/api/v1/widget-config'
      path: '/api/v1/widget-config'
      fullPath: '/api/v1/widget-config'
      preLoaderRoute: typeof ApiV1WidgetConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/p/$projectId': {
      id: '/app/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/app/p/$projectId'
      preLoaderRoute: typeof AppPProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/projects/$projectId/export': {
      id: '/api/projects/$projectId/export'
      path: '/api/projects/$projectId/export'
      fullPath: '/api/projects/$projectId/export'
      preLoaderRoute: typeof ApiProjectsProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/p/$projectId/': {
      id: '/app/p/$projectId/'
      path: '/'
      fullPath: '/app/p/$projectId/'
      preLoaderRoute: typeof AppPProjectIdIndexRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/insights': {
      id: '/app/p/$projectId/insights'
      path: '/insights'
      fullPath: '/app/p/$projectId/insights'
      preLoaderRoute: typeof AppPProjectIdInsightsRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/install': {
      id: '/app/p/$projectId/install'
      path: '/install'
      fullPath: '/app/p/$projectId/install'
      preLoaderRoute: typeof AppPProjectIdInstallRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/settings': {
      id: '/app/p/$projectId/settings'
      path: '/settings'
      fullPath: '/app/p/$projectId/settings'
      preLoaderRoute: typeof AppPProjectIdSettingsRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
  }
}

interface AppPProjectIdRouteChildren {
  AppPProjectIdInsightsRoute: typeof AppPProjectIdInsightsRoute
  AppPProjectIdInstallRoute: typeof AppPProjectIdInstallRoute
  AppPProjectIdSettingsRoute: typeof AppPProjectIdSettingsRoute
  AppPProjectIdIndexRoute: typeof AppPProjectIdIndexRoute
}

const AppPProjectIdRouteChildren: AppPProjectIdRouteChildren = {
  AppPProjectIdInsightsRoute: AppPProjectIdInsightsRoute,
  AppPProjectIdInstallRoute: AppPProjectIdInstallRoute,
  AppPProjectIdSettingsRoute: AppPProjectIdSettingsRoute,
  AppPProjectIdIndexRoute: AppPProjectIdIndexRoute,
}

const AppPProjectIdRouteWithChildren = AppPProjectIdRoute._addFileChildren(
  AppPProjectIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppNewRoute: typeof AppNewRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPProjectIdRoute: typeof AppPProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppNewRoute: AppNewRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppPProjectIdRoute: AppPProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  BSlugRoute: BSlugRoute,
  FSlugRoute: FSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiV1FeedbackRoute: ApiV1FeedbackRoute,
  ApiV1WidgetConfigRoute: ApiV1WidgetConfigRoute,
  ApiProjectsProjectIdExportRoute: ApiProjectsProjectIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
